/* posse_dc module*/

<?php
/* function to render the blog_posts on homepage */
function posse_dc_preprocess(&$variables, $hook) {
  $blog_block = views_embed_view('blog_posts', 'block_1');
  $variables['blog_block'] = $blog_block; // put it in twig variable

/* render portfolio_block on the homepage */
  $portfolio_block = views_embed_view('portfolio', 'block_1');
  $variables['portfolio_block'] = $portfolio_block;
}
